alias e=$EDITOR
alias be='bundle exec'
alias gl='BUNDLE_GEMFILE=Gemfile.local'
alias et='RAILS_ENV=test'
alias ed='RAILS_ENV=dev'
alias tbe='et be'
alias tbec='et be cucumber -p all'
alias tber='et be rspec'
alias dbe='ed be'
alias rspec='rspec --format documentation'
alias sudo='sudo '
