#!/bin/bash

INPUT_DEVICE="'Capture'"
YOUR_USERNAME="nimaai"

if amixer sget $INPUT_DEVICE,0 | grep '\[on\]' ; then
    amixer sset $INPUT_DEVICE,0 toggle
    echo "0 blink" | sudo tee /proc/acpi/ibm/led
    # su $YOUR_USERNAME -c 'DISPLAY=":0.0" notify-send -t 50 \
    #         -i microphone-sensitivity-muted-symbolic "Mic MUTED"'
    DISPLAY=":0.0" notify-send -t 50 -i microphone-sensitivity-muted-symbolic "Mic MUTED"
else
    amixer sset $INPUT_DEVICE,0 toggle
    echo "0 on" | sudo tee /proc/acpi/ibm/led
    # su $YOUR_USERNAME -c 'DISPLAY=":0.0" notify-send -t 50 \
    #         -i microphone-sensitivity-high-symbolic "Mic ON"'
    DISPLAY=":0.0" notify-send -t 50 -i microphone-sensitivity-high-symbolic "Mic ON"
fi
