#!/bin/sh

case "$1" in
  true)

    # set cpufrequtils governer
    cpufreq-set -c 0 -g powersave
    cpufreq-set -c 1 -g powersave
    cpufreq-set -c 2 -g powersave
    cpufreq-set -c 3 -g powersave
    ;;

  false)

    # set cpufrequtils governer
    cpufreq-set -c 0 -g ondemand
    cpufreq-set -c 1 -g ondemand
    cpufreq-set -c 2 -g ondemand
    cpufreq-set -c 3 -g ondemand
    ;;
esac
