#!/bin/bash

# So that the top buttons don't make the pointer move
synclient AreaTopEdge=2400

# Top right edge: right button
synclient RightButtonAreaRight=4858
synclient RightButtonAreaLeft=4000
synclient RightButtonAreaBottom=2500
synclient RightButtonAreaTop=0

# top center edge -> middle button
synclient MiddleButtonAreaRight=3813
synclient MiddleButtonAreaLeft=2770
synclient MiddleButtonAreaBottom=2500
synclient MiddleButtonAreaTop=0

# # this sets up the single, double and triple taps to match up to left, right and middle mouse clicks respectively
# synclient TapButton1=1
# synclient TapButton2=3
# ## three fingers for the middle button
# synclient TapButton3=2

# ## enables palm detection while you’re typing with some reasonable settings
# synclient PalmDetect=1
# synclient PalmMinWidth=5
# synclient PalmMinZ=40

# ## drag lock
# synclient LockedDrags=1

# ## prevents too many intentional clicks
# synclient PalmDetect=0

# synclient VertEdgeScroll=0
# # "natural" vertical and horizontal scrolling
# synclient VertTwoFingerScroll=1
# synclient VertScrollDelta=75
# synclient HorizTwoFingerScroll=1
# synclient HorizScrollDelta=75

# ## accurate tap-to-click!
# synclient FingerLow=50
# synclient FingerHigh=55

# ## reduces movement during and between taps
# synclient HorizHysteresis=50
# synclient VertHysteresis=50

# synclient MinSpeed=1
# synclient MaxSpeed=1

# # synclient AccelerationProfile=2
# synclient ConstantDeceleration=4

# syndaemon monitors keyboard activity and disables the touchpad while typing
# syndaemon -t -k -R -i 1 &
