alias e=$EDITOR
alias bx='bundle exec'
alias gl='BUNDLE_GEMFILE=Gemfile.local'
alias et='RAILS_ENV=test'
alias ed='RAILS_ENV=dev'
alias c='cucumber -p default'
alias tbx='et be'
alias tbxc='et be cucumber'
alias tbxr='et be rspec'
alias dbx='ed be'
alias rspec='rspec --format documentation'
alias sudo='sudo '
alias zls='wfica ~/launch.ica'
alias npm-exec='PATH=$(npm bin):$HOME/node_modules/.bin:$PATH'
alias leinrp='cat .nrepl-port | xargs lein repl :start :port'
alias rm='echo "This is not the command you are looking for."; false'
